/*
 * generated by Xtext 2.35.0
 */
package org.xtext.example.hdl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.hdl.parser.antlr.internal.InternalHDLParser;
import org.xtext.example.hdl.services.HDLGrammarAccess;

public class HDLParser extends AbstractAntlrParser {

	@Inject
	private HDLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalHDLParser createParser(XtextTokenStream stream) {
		return new InternalHDLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public HDLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(HDLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
