/*
 * generated by Xtext 2.35.0
 */
package org.xtext.example.hdl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.hdl.HDLRuntimeModule;
import org.xtext.example.hdl.HDLStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class HDLIdeSetup extends HDLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new HDLRuntimeModule(), new HDLIdeModule()));
	}
	
}
