/**
 * generated by Xtext 2.35.0
 */
package org.xtext.example.hdl.hDL.impl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

import org.xtext.example.hdl.hDL.HDLFactory;
import org.xtext.example.hdl.hDL.HDLPackage;
import org.xtext.example.hdl.hDL.Model;
import org.xtext.example.hdl.hDL.PTArchDecl;
import org.xtext.example.hdl.hDL.PTEntityDecl;
import org.xtext.example.hdl.hDL.PTIdentifier;
import org.xtext.example.hdl.hDL.PTSignalAssign;
import org.xtext.example.hdl.hDL.PTSignalDecl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class HDLPackageImpl extends EPackageImpl implements HDLPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass modelEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass ptEntityDeclEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass ptArchDeclEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass ptSignalDeclEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass ptSignalAssignEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass ptIdentifierEClass = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see org.xtext.example.hdl.hDL.HDLPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private HDLPackageImpl()
  {
    super(eNS_URI, HDLFactory.eINSTANCE);
  }
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link HDLPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static HDLPackage init()
  {
    if (isInited) return (HDLPackage)EPackage.Registry.INSTANCE.getEPackage(HDLPackage.eNS_URI);

    // Obtain or create and register package
    Object registeredHDLPackage = EPackage.Registry.INSTANCE.get(eNS_URI);
    HDLPackageImpl theHDLPackage = registeredHDLPackage instanceof HDLPackageImpl ? (HDLPackageImpl)registeredHDLPackage : new HDLPackageImpl();

    isInited = true;

    // Create package meta-data objects
    theHDLPackage.createPackageContents();

    // Initialize created meta-data
    theHDLPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theHDLPackage.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(HDLPackage.eNS_URI, theHDLPackage);
    return theHDLPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getModel()
  {
    return modelEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModel_EntityDecl()
  {
    return (EReference)modelEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModel_ArchDecl()
  {
    return (EReference)modelEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getPTEntityDecl()
  {
    return ptEntityDeclEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getPTEntityDecl_Name()
  {
    return (EAttribute)ptEntityDeclEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getPTArchDecl()
  {
    return ptArchDeclEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getPTArchDecl_EntityId()
  {
    return (EReference)ptArchDeclEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getPTArchDecl_SignalDecls()
  {
    return (EReference)ptArchDeclEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getPTArchDecl_SignalAssign()
  {
    return (EReference)ptArchDeclEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getPTSignalDecl()
  {
    return ptSignalDeclEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getPTSignalDecl_Name()
  {
    return (EAttribute)ptSignalDeclEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getPTSignalDecl_SignalType()
  {
    return (EAttribute)ptSignalDeclEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getPTSignalAssign()
  {
    return ptSignalAssignEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getPTSignalAssign_Lhs()
  {
    return (EReference)ptSignalAssignEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getPTSignalAssign_Rhs()
  {
    return (EReference)ptSignalAssignEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getPTIdentifier()
  {
    return ptIdentifierEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getPTIdentifier_Id()
  {
    return (EReference)ptIdentifierEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public HDLFactory getHDLFactory()
  {
    return (HDLFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    modelEClass = createEClass(MODEL);
    createEReference(modelEClass, MODEL__ENTITY_DECL);
    createEReference(modelEClass, MODEL__ARCH_DECL);

    ptEntityDeclEClass = createEClass(PT_ENTITY_DECL);
    createEAttribute(ptEntityDeclEClass, PT_ENTITY_DECL__NAME);

    ptArchDeclEClass = createEClass(PT_ARCH_DECL);
    createEReference(ptArchDeclEClass, PT_ARCH_DECL__ENTITY_ID);
    createEReference(ptArchDeclEClass, PT_ARCH_DECL__SIGNAL_DECLS);
    createEReference(ptArchDeclEClass, PT_ARCH_DECL__SIGNAL_ASSIGN);

    ptSignalDeclEClass = createEClass(PT_SIGNAL_DECL);
    createEAttribute(ptSignalDeclEClass, PT_SIGNAL_DECL__NAME);
    createEAttribute(ptSignalDeclEClass, PT_SIGNAL_DECL__SIGNAL_TYPE);

    ptSignalAssignEClass = createEClass(PT_SIGNAL_ASSIGN);
    createEReference(ptSignalAssignEClass, PT_SIGNAL_ASSIGN__LHS);
    createEReference(ptSignalAssignEClass, PT_SIGNAL_ASSIGN__RHS);

    ptIdentifierEClass = createEClass(PT_IDENTIFIER);
    createEReference(ptIdentifierEClass, PT_IDENTIFIER__ID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes

    // Initialize classes and features; add operations and parameters
    initEClass(modelEClass, Model.class, "Model", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getModel_EntityDecl(), this.getPTEntityDecl(), null, "entityDecl", null, 0, 1, Model.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getModel_ArchDecl(), this.getPTArchDecl(), null, "archDecl", null, 0, 1, Model.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(ptEntityDeclEClass, PTEntityDecl.class, "PTEntityDecl", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getPTEntityDecl_Name(), ecorePackage.getEString(), "name", null, 0, 1, PTEntityDecl.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(ptArchDeclEClass, PTArchDecl.class, "PTArchDecl", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getPTArchDecl_EntityId(), this.getPTEntityDecl(), null, "entityId", null, 0, 1, PTArchDecl.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getPTArchDecl_SignalDecls(), this.getPTSignalDecl(), null, "signalDecls", null, 0, -1, PTArchDecl.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getPTArchDecl_SignalAssign(), this.getPTSignalAssign(), null, "signalAssign", null, 0, -1, PTArchDecl.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(ptSignalDeclEClass, PTSignalDecl.class, "PTSignalDecl", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getPTSignalDecl_Name(), ecorePackage.getEString(), "name", null, 0, 1, PTSignalDecl.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getPTSignalDecl_SignalType(), ecorePackage.getEString(), "signalType", null, 0, 1, PTSignalDecl.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(ptSignalAssignEClass, PTSignalAssign.class, "PTSignalAssign", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getPTSignalAssign_Lhs(), this.getPTIdentifier(), null, "lhs", null, 0, 1, PTSignalAssign.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getPTSignalAssign_Rhs(), this.getPTIdentifier(), null, "rhs", null, 0, 1, PTSignalAssign.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(ptIdentifierEClass, PTIdentifier.class, "PTIdentifier", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getPTIdentifier_Id(), this.getPTSignalDecl(), null, "id", null, 0, 1, PTIdentifier.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Create resource
    createResource(eNS_URI);
  }

} //HDLPackageImpl
