/**
 * generated by Xtext 2.35.0
 */
package org.xtext.example.hdl.hDL.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.hdl.hDL.HDLPackage;
import org.xtext.example.hdl.hDL.Model;
import org.xtext.example.hdl.hDL.PTArchDecl;
import org.xtext.example.hdl.hDL.PTEntityDecl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.hdl.hDL.impl.ModelImpl#getEntityDecl <em>Entity Decl</em>}</li>
 *   <li>{@link org.xtext.example.hdl.hDL.impl.ModelImpl#getArchDecl <em>Arch Decl</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ModelImpl extends MinimalEObjectImpl.Container implements Model
{
  /**
   * The cached value of the '{@link #getEntityDecl() <em>Entity Decl</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEntityDecl()
   * @generated
   * @ordered
   */
  protected PTEntityDecl entityDecl;

  /**
   * The cached value of the '{@link #getArchDecl() <em>Arch Decl</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getArchDecl()
   * @generated
   * @ordered
   */
  protected PTArchDecl archDecl;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ModelImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return HDLPackage.Literals.MODEL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PTEntityDecl getEntityDecl()
  {
    return entityDecl;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetEntityDecl(PTEntityDecl newEntityDecl, NotificationChain msgs)
  {
    PTEntityDecl oldEntityDecl = entityDecl;
    entityDecl = newEntityDecl;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, HDLPackage.MODEL__ENTITY_DECL, oldEntityDecl, newEntityDecl);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEntityDecl(PTEntityDecl newEntityDecl)
  {
    if (newEntityDecl != entityDecl)
    {
      NotificationChain msgs = null;
      if (entityDecl != null)
        msgs = ((InternalEObject)entityDecl).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - HDLPackage.MODEL__ENTITY_DECL, null, msgs);
      if (newEntityDecl != null)
        msgs = ((InternalEObject)newEntityDecl).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - HDLPackage.MODEL__ENTITY_DECL, null, msgs);
      msgs = basicSetEntityDecl(newEntityDecl, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, HDLPackage.MODEL__ENTITY_DECL, newEntityDecl, newEntityDecl));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PTArchDecl getArchDecl()
  {
    return archDecl;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetArchDecl(PTArchDecl newArchDecl, NotificationChain msgs)
  {
    PTArchDecl oldArchDecl = archDecl;
    archDecl = newArchDecl;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, HDLPackage.MODEL__ARCH_DECL, oldArchDecl, newArchDecl);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setArchDecl(PTArchDecl newArchDecl)
  {
    if (newArchDecl != archDecl)
    {
      NotificationChain msgs = null;
      if (archDecl != null)
        msgs = ((InternalEObject)archDecl).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - HDLPackage.MODEL__ARCH_DECL, null, msgs);
      if (newArchDecl != null)
        msgs = ((InternalEObject)newArchDecl).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - HDLPackage.MODEL__ARCH_DECL, null, msgs);
      msgs = basicSetArchDecl(newArchDecl, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, HDLPackage.MODEL__ARCH_DECL, newArchDecl, newArchDecl));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case HDLPackage.MODEL__ENTITY_DECL:
        return basicSetEntityDecl(null, msgs);
      case HDLPackage.MODEL__ARCH_DECL:
        return basicSetArchDecl(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case HDLPackage.MODEL__ENTITY_DECL:
        return getEntityDecl();
      case HDLPackage.MODEL__ARCH_DECL:
        return getArchDecl();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case HDLPackage.MODEL__ENTITY_DECL:
        setEntityDecl((PTEntityDecl)newValue);
        return;
      case HDLPackage.MODEL__ARCH_DECL:
        setArchDecl((PTArchDecl)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case HDLPackage.MODEL__ENTITY_DECL:
        setEntityDecl((PTEntityDecl)null);
        return;
      case HDLPackage.MODEL__ARCH_DECL:
        setArchDecl((PTArchDecl)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case HDLPackage.MODEL__ENTITY_DECL:
        return entityDecl != null;
      case HDLPackage.MODEL__ARCH_DECL:
        return archDecl != null;
    }
    return super.eIsSet(featureID);
  }

} //ModelImpl
