/**
 * generated by Xtext 2.35.0
 */
package org.xtext.example.hdl.hDL.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.hdl.hDL.HDLPackage;
import org.xtext.example.hdl.hDL.PTSignalDecl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>PT Signal Decl</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.hdl.hDL.impl.PTSignalDeclImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.hdl.hDL.impl.PTSignalDeclImpl#getSignalType <em>Signal Type</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PTSignalDeclImpl extends MinimalEObjectImpl.Container implements PTSignalDecl
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getSignalType() <em>Signal Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSignalType()
   * @generated
   * @ordered
   */
  protected static final String SIGNAL_TYPE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getSignalType() <em>Signal Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSignalType()
   * @generated
   * @ordered
   */
  protected String signalType = SIGNAL_TYPE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PTSignalDeclImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return HDLPackage.Literals.PT_SIGNAL_DECL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, HDLPackage.PT_SIGNAL_DECL__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getSignalType()
  {
    return signalType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSignalType(String newSignalType)
  {
    String oldSignalType = signalType;
    signalType = newSignalType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, HDLPackage.PT_SIGNAL_DECL__SIGNAL_TYPE, oldSignalType, signalType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case HDLPackage.PT_SIGNAL_DECL__NAME:
        return getName();
      case HDLPackage.PT_SIGNAL_DECL__SIGNAL_TYPE:
        return getSignalType();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case HDLPackage.PT_SIGNAL_DECL__NAME:
        setName((String)newValue);
        return;
      case HDLPackage.PT_SIGNAL_DECL__SIGNAL_TYPE:
        setSignalType((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case HDLPackage.PT_SIGNAL_DECL__NAME:
        setName(NAME_EDEFAULT);
        return;
      case HDLPackage.PT_SIGNAL_DECL__SIGNAL_TYPE:
        setSignalType(SIGNAL_TYPE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case HDLPackage.PT_SIGNAL_DECL__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case HDLPackage.PT_SIGNAL_DECL__SIGNAL_TYPE:
        return SIGNAL_TYPE_EDEFAULT == null ? signalType != null : !SIGNAL_TYPE_EDEFAULT.equals(signalType);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", signalType: ");
    result.append(signalType);
    result.append(')');
    return result.toString();
  }

} //PTSignalDeclImpl
