/*
 * generated by Xtext 2.35.0
 */
package org.xtext.example.hdl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.example.hdl.ui.internal.HdlActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class HDLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(HdlActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		HdlActivator activator = HdlActivator.getInstance();
		return activator != null ? activator.getInjector(HdlActivator.ORG_XTEXT_EXAMPLE_HDL_HDL) : null;
	}

}
