/*
 * generated by Xtext 2.35.0
 */
package org.xtext.example.hdl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class HDLStandaloneSetup extends HDLStandaloneSetupGenerated {

	public static void doSetup() {
		new HDLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
