/**
 * generated by Xtext 2.35.0
 */
package org.xtext.example.hdl.hDL;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.example.hdl.hDL.HDLPackage
 * @generated
 */
public interface HDLFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  HDLFactory eINSTANCE = org.xtext.example.hdl.hDL.impl.HDLFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>PT Entity Decl</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>PT Entity Decl</em>'.
   * @generated
   */
  PTEntityDecl createPTEntityDecl();

  /**
   * Returns a new object of class '<em>PT Arch Decl</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>PT Arch Decl</em>'.
   * @generated
   */
  PTArchDecl createPTArchDecl();

  /**
   * Returns a new object of class '<em>PT Signal Decl</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>PT Signal Decl</em>'.
   * @generated
   */
  PTSignalDecl createPTSignalDecl();

  /**
   * Returns a new object of class '<em>PT Signal Assign</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>PT Signal Assign</em>'.
   * @generated
   */
  PTSignalAssign createPTSignalAssign();

  /**
   * Returns a new object of class '<em>PT Identifier</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>PT Identifier</em>'.
   * @generated
   */
  PTIdentifier createPTIdentifier();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  HDLPackage getHDLPackage();

} //HDLFactory
