/**
 * generated by Xtext 2.35.0
 */
package org.xtext.example.hdl.hDL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.hdl.hDL.HDLFactory
 * @model kind="package"
 * @generated
 */
public interface HDLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "hDL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/hdl/HDL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "hDL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  HDLPackage eINSTANCE = org.xtext.example.hdl.hDL.impl.HDLPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.hdl.hDL.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.hdl.hDL.impl.ModelImpl
   * @see org.xtext.example.hdl.hDL.impl.HDLPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Entity Decl</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__ENTITY_DECL = 0;

  /**
   * The feature id for the '<em><b>Arch Decl</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__ARCH_DECL = 1;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.hdl.hDL.impl.PTEntityDeclImpl <em>PT Entity Decl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.hdl.hDL.impl.PTEntityDeclImpl
   * @see org.xtext.example.hdl.hDL.impl.HDLPackageImpl#getPTEntityDecl()
   * @generated
   */
  int PT_ENTITY_DECL = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PT_ENTITY_DECL__NAME = 0;

  /**
   * The number of structural features of the '<em>PT Entity Decl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PT_ENTITY_DECL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.hdl.hDL.impl.PTArchDeclImpl <em>PT Arch Decl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.hdl.hDL.impl.PTArchDeclImpl
   * @see org.xtext.example.hdl.hDL.impl.HDLPackageImpl#getPTArchDecl()
   * @generated
   */
  int PT_ARCH_DECL = 2;

  /**
   * The feature id for the '<em><b>Entity Id</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PT_ARCH_DECL__ENTITY_ID = 0;

  /**
   * The feature id for the '<em><b>Signal Decls</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PT_ARCH_DECL__SIGNAL_DECLS = 1;

  /**
   * The feature id for the '<em><b>Signal Assign</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PT_ARCH_DECL__SIGNAL_ASSIGN = 2;

  /**
   * The number of structural features of the '<em>PT Arch Decl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PT_ARCH_DECL_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.hdl.hDL.impl.PTSignalDeclImpl <em>PT Signal Decl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.hdl.hDL.impl.PTSignalDeclImpl
   * @see org.xtext.example.hdl.hDL.impl.HDLPackageImpl#getPTSignalDecl()
   * @generated
   */
  int PT_SIGNAL_DECL = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PT_SIGNAL_DECL__NAME = 0;

  /**
   * The feature id for the '<em><b>Signal Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PT_SIGNAL_DECL__SIGNAL_TYPE = 1;

  /**
   * The number of structural features of the '<em>PT Signal Decl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PT_SIGNAL_DECL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.hdl.hDL.impl.PTSignalAssignImpl <em>PT Signal Assign</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.hdl.hDL.impl.PTSignalAssignImpl
   * @see org.xtext.example.hdl.hDL.impl.HDLPackageImpl#getPTSignalAssign()
   * @generated
   */
  int PT_SIGNAL_ASSIGN = 4;

  /**
   * The feature id for the '<em><b>Lhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PT_SIGNAL_ASSIGN__LHS = 0;

  /**
   * The feature id for the '<em><b>Rhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PT_SIGNAL_ASSIGN__RHS = 1;

  /**
   * The number of structural features of the '<em>PT Signal Assign</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PT_SIGNAL_ASSIGN_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.hdl.hDL.impl.PTIdentifierImpl <em>PT Identifier</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.hdl.hDL.impl.PTIdentifierImpl
   * @see org.xtext.example.hdl.hDL.impl.HDLPackageImpl#getPTIdentifier()
   * @generated
   */
  int PT_IDENTIFIER = 5;

  /**
   * The feature id for the '<em><b>Id</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PT_IDENTIFIER__ID = 0;

  /**
   * The number of structural features of the '<em>PT Identifier</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PT_IDENTIFIER_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.xtext.example.hdl.hDL.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.example.hdl.hDL.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.hdl.hDL.Model#getEntityDecl <em>Entity Decl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Entity Decl</em>'.
   * @see org.xtext.example.hdl.hDL.Model#getEntityDecl()
   * @see #getModel()
   * @generated
   */
  EReference getModel_EntityDecl();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.hdl.hDL.Model#getArchDecl <em>Arch Decl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Arch Decl</em>'.
   * @see org.xtext.example.hdl.hDL.Model#getArchDecl()
   * @see #getModel()
   * @generated
   */
  EReference getModel_ArchDecl();

  /**
   * Returns the meta object for class '{@link org.xtext.example.hdl.hDL.PTEntityDecl <em>PT Entity Decl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>PT Entity Decl</em>'.
   * @see org.xtext.example.hdl.hDL.PTEntityDecl
   * @generated
   */
  EClass getPTEntityDecl();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.hdl.hDL.PTEntityDecl#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.hdl.hDL.PTEntityDecl#getName()
   * @see #getPTEntityDecl()
   * @generated
   */
  EAttribute getPTEntityDecl_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.hdl.hDL.PTArchDecl <em>PT Arch Decl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>PT Arch Decl</em>'.
   * @see org.xtext.example.hdl.hDL.PTArchDecl
   * @generated
   */
  EClass getPTArchDecl();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.hdl.hDL.PTArchDecl#getEntityId <em>Entity Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Entity Id</em>'.
   * @see org.xtext.example.hdl.hDL.PTArchDecl#getEntityId()
   * @see #getPTArchDecl()
   * @generated
   */
  EReference getPTArchDecl_EntityId();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.hdl.hDL.PTArchDecl#getSignalDecls <em>Signal Decls</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Signal Decls</em>'.
   * @see org.xtext.example.hdl.hDL.PTArchDecl#getSignalDecls()
   * @see #getPTArchDecl()
   * @generated
   */
  EReference getPTArchDecl_SignalDecls();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.hdl.hDL.PTArchDecl#getSignalAssign <em>Signal Assign</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Signal Assign</em>'.
   * @see org.xtext.example.hdl.hDL.PTArchDecl#getSignalAssign()
   * @see #getPTArchDecl()
   * @generated
   */
  EReference getPTArchDecl_SignalAssign();

  /**
   * Returns the meta object for class '{@link org.xtext.example.hdl.hDL.PTSignalDecl <em>PT Signal Decl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>PT Signal Decl</em>'.
   * @see org.xtext.example.hdl.hDL.PTSignalDecl
   * @generated
   */
  EClass getPTSignalDecl();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.hdl.hDL.PTSignalDecl#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.hdl.hDL.PTSignalDecl#getName()
   * @see #getPTSignalDecl()
   * @generated
   */
  EAttribute getPTSignalDecl_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.hdl.hDL.PTSignalDecl#getSignalType <em>Signal Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Signal Type</em>'.
   * @see org.xtext.example.hdl.hDL.PTSignalDecl#getSignalType()
   * @see #getPTSignalDecl()
   * @generated
   */
  EAttribute getPTSignalDecl_SignalType();

  /**
   * Returns the meta object for class '{@link org.xtext.example.hdl.hDL.PTSignalAssign <em>PT Signal Assign</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>PT Signal Assign</em>'.
   * @see org.xtext.example.hdl.hDL.PTSignalAssign
   * @generated
   */
  EClass getPTSignalAssign();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.hdl.hDL.PTSignalAssign#getLhs <em>Lhs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Lhs</em>'.
   * @see org.xtext.example.hdl.hDL.PTSignalAssign#getLhs()
   * @see #getPTSignalAssign()
   * @generated
   */
  EReference getPTSignalAssign_Lhs();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.hdl.hDL.PTSignalAssign#getRhs <em>Rhs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rhs</em>'.
   * @see org.xtext.example.hdl.hDL.PTSignalAssign#getRhs()
   * @see #getPTSignalAssign()
   * @generated
   */
  EReference getPTSignalAssign_Rhs();

  /**
   * Returns the meta object for class '{@link org.xtext.example.hdl.hDL.PTIdentifier <em>PT Identifier</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>PT Identifier</em>'.
   * @see org.xtext.example.hdl.hDL.PTIdentifier
   * @generated
   */
  EClass getPTIdentifier();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.hdl.hDL.PTIdentifier#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Id</em>'.
   * @see org.xtext.example.hdl.hDL.PTIdentifier#getId()
   * @see #getPTIdentifier()
   * @generated
   */
  EReference getPTIdentifier_Id();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  HDLFactory getHDLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.hdl.hDL.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.hdl.hDL.impl.ModelImpl
     * @see org.xtext.example.hdl.hDL.impl.HDLPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Entity Decl</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__ENTITY_DECL = eINSTANCE.getModel_EntityDecl();

    /**
     * The meta object literal for the '<em><b>Arch Decl</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__ARCH_DECL = eINSTANCE.getModel_ArchDecl();

    /**
     * The meta object literal for the '{@link org.xtext.example.hdl.hDL.impl.PTEntityDeclImpl <em>PT Entity Decl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.hdl.hDL.impl.PTEntityDeclImpl
     * @see org.xtext.example.hdl.hDL.impl.HDLPackageImpl#getPTEntityDecl()
     * @generated
     */
    EClass PT_ENTITY_DECL = eINSTANCE.getPTEntityDecl();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PT_ENTITY_DECL__NAME = eINSTANCE.getPTEntityDecl_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.hdl.hDL.impl.PTArchDeclImpl <em>PT Arch Decl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.hdl.hDL.impl.PTArchDeclImpl
     * @see org.xtext.example.hdl.hDL.impl.HDLPackageImpl#getPTArchDecl()
     * @generated
     */
    EClass PT_ARCH_DECL = eINSTANCE.getPTArchDecl();

    /**
     * The meta object literal for the '<em><b>Entity Id</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PT_ARCH_DECL__ENTITY_ID = eINSTANCE.getPTArchDecl_EntityId();

    /**
     * The meta object literal for the '<em><b>Signal Decls</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PT_ARCH_DECL__SIGNAL_DECLS = eINSTANCE.getPTArchDecl_SignalDecls();

    /**
     * The meta object literal for the '<em><b>Signal Assign</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PT_ARCH_DECL__SIGNAL_ASSIGN = eINSTANCE.getPTArchDecl_SignalAssign();

    /**
     * The meta object literal for the '{@link org.xtext.example.hdl.hDL.impl.PTSignalDeclImpl <em>PT Signal Decl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.hdl.hDL.impl.PTSignalDeclImpl
     * @see org.xtext.example.hdl.hDL.impl.HDLPackageImpl#getPTSignalDecl()
     * @generated
     */
    EClass PT_SIGNAL_DECL = eINSTANCE.getPTSignalDecl();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PT_SIGNAL_DECL__NAME = eINSTANCE.getPTSignalDecl_Name();

    /**
     * The meta object literal for the '<em><b>Signal Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PT_SIGNAL_DECL__SIGNAL_TYPE = eINSTANCE.getPTSignalDecl_SignalType();

    /**
     * The meta object literal for the '{@link org.xtext.example.hdl.hDL.impl.PTSignalAssignImpl <em>PT Signal Assign</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.hdl.hDL.impl.PTSignalAssignImpl
     * @see org.xtext.example.hdl.hDL.impl.HDLPackageImpl#getPTSignalAssign()
     * @generated
     */
    EClass PT_SIGNAL_ASSIGN = eINSTANCE.getPTSignalAssign();

    /**
     * The meta object literal for the '<em><b>Lhs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PT_SIGNAL_ASSIGN__LHS = eINSTANCE.getPTSignalAssign_Lhs();

    /**
     * The meta object literal for the '<em><b>Rhs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PT_SIGNAL_ASSIGN__RHS = eINSTANCE.getPTSignalAssign_Rhs();

    /**
     * The meta object literal for the '{@link org.xtext.example.hdl.hDL.impl.PTIdentifierImpl <em>PT Identifier</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.hdl.hDL.impl.PTIdentifierImpl
     * @see org.xtext.example.hdl.hDL.impl.HDLPackageImpl#getPTIdentifier()
     * @generated
     */
    EClass PT_IDENTIFIER = eINSTANCE.getPTIdentifier();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PT_IDENTIFIER__ID = eINSTANCE.getPTIdentifier_Id();

  }

} //HDLPackage
