/**
 * generated by Xtext 2.35.0
 */
package org.xtext.example.hdl.hDL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.hdl.hDL.Model#getEntityDecl <em>Entity Decl</em>}</li>
 *   <li>{@link org.xtext.example.hdl.hDL.Model#getArchDecl <em>Arch Decl</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.hdl.hDL.HDLPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Entity Decl</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entity Decl</em>' containment reference.
   * @see #setEntityDecl(PTEntityDecl)
   * @see org.xtext.example.hdl.hDL.HDLPackage#getModel_EntityDecl()
   * @model containment="true"
   * @generated
   */
  PTEntityDecl getEntityDecl();

  /**
   * Sets the value of the '{@link org.xtext.example.hdl.hDL.Model#getEntityDecl <em>Entity Decl</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Entity Decl</em>' containment reference.
   * @see #getEntityDecl()
   * @generated
   */
  void setEntityDecl(PTEntityDecl value);

  /**
   * Returns the value of the '<em><b>Arch Decl</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Arch Decl</em>' containment reference.
   * @see #setArchDecl(PTArchDecl)
   * @see org.xtext.example.hdl.hDL.HDLPackage#getModel_ArchDecl()
   * @model containment="true"
   * @generated
   */
  PTArchDecl getArchDecl();

  /**
   * Sets the value of the '{@link org.xtext.example.hdl.hDL.Model#getArchDecl <em>Arch Decl</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Arch Decl</em>' containment reference.
   * @see #getArchDecl()
   * @generated
   */
  void setArchDecl(PTArchDecl value);

} // Model
