/**
 * generated by Xtext 2.35.0
 */
package org.xtext.example.hdl.hDL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>PT Arch Decl</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.hdl.hDL.PTArchDecl#getEntityId <em>Entity Id</em>}</li>
 *   <li>{@link org.xtext.example.hdl.hDL.PTArchDecl#getSignalDecls <em>Signal Decls</em>}</li>
 *   <li>{@link org.xtext.example.hdl.hDL.PTArchDecl#getSignalAssign <em>Signal Assign</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.hdl.hDL.HDLPackage#getPTArchDecl()
 * @model
 * @generated
 */
public interface PTArchDecl extends EObject
{
  /**
   * Returns the value of the '<em><b>Entity Id</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entity Id</em>' reference.
   * @see #setEntityId(PTEntityDecl)
   * @see org.xtext.example.hdl.hDL.HDLPackage#getPTArchDecl_EntityId()
   * @model
   * @generated
   */
  PTEntityDecl getEntityId();

  /**
   * Sets the value of the '{@link org.xtext.example.hdl.hDL.PTArchDecl#getEntityId <em>Entity Id</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Entity Id</em>' reference.
   * @see #getEntityId()
   * @generated
   */
  void setEntityId(PTEntityDecl value);

  /**
   * Returns the value of the '<em><b>Signal Decls</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.hdl.hDL.PTSignalDecl}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Signal Decls</em>' containment reference list.
   * @see org.xtext.example.hdl.hDL.HDLPackage#getPTArchDecl_SignalDecls()
   * @model containment="true"
   * @generated
   */
  EList<PTSignalDecl> getSignalDecls();

  /**
   * Returns the value of the '<em><b>Signal Assign</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.hdl.hDL.PTSignalAssign}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Signal Assign</em>' containment reference list.
   * @see org.xtext.example.hdl.hDL.HDLPackage#getPTArchDecl_SignalAssign()
   * @model containment="true"
   * @generated
   */
  EList<PTSignalAssign> getSignalAssign();

} // PTArchDecl
