/**
 * generated by Xtext 2.35.0
 */
package org.xtext.example.hdl.hDL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>PT Identifier</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.hdl.hDL.PTIdentifier#getId <em>Id</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.hdl.hDL.HDLPackage#getPTIdentifier()
 * @model
 * @generated
 */
public interface PTIdentifier extends EObject
{
  /**
   * Returns the value of the '<em><b>Id</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' reference.
   * @see #setId(PTSignalDecl)
   * @see org.xtext.example.hdl.hDL.HDLPackage#getPTIdentifier_Id()
   * @model
   * @generated
   */
  PTSignalDecl getId();

  /**
   * Sets the value of the '{@link org.xtext.example.hdl.hDL.PTIdentifier#getId <em>Id</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' reference.
   * @see #getId()
   * @generated
   */
  void setId(PTSignalDecl value);

} // PTIdentifier
