/**
 * generated by Xtext 2.35.0
 */
package org.xtext.example.hdl.hDL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>PT Signal Assign</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.hdl.hDL.PTSignalAssign#getLhs <em>Lhs</em>}</li>
 *   <li>{@link org.xtext.example.hdl.hDL.PTSignalAssign#getRhs <em>Rhs</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.hdl.hDL.HDLPackage#getPTSignalAssign()
 * @model
 * @generated
 */
public interface PTSignalAssign extends EObject
{
  /**
   * Returns the value of the '<em><b>Lhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lhs</em>' containment reference.
   * @see #setLhs(PTIdentifier)
   * @see org.xtext.example.hdl.hDL.HDLPackage#getPTSignalAssign_Lhs()
   * @model containment="true"
   * @generated
   */
  PTIdentifier getLhs();

  /**
   * Sets the value of the '{@link org.xtext.example.hdl.hDL.PTSignalAssign#getLhs <em>Lhs</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lhs</em>' containment reference.
   * @see #getLhs()
   * @generated
   */
  void setLhs(PTIdentifier value);

  /**
   * Returns the value of the '<em><b>Rhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rhs</em>' containment reference.
   * @see #setRhs(PTIdentifier)
   * @see org.xtext.example.hdl.hDL.HDLPackage#getPTSignalAssign_Rhs()
   * @model containment="true"
   * @generated
   */
  PTIdentifier getRhs();

  /**
   * Sets the value of the '{@link org.xtext.example.hdl.hDL.PTSignalAssign#getRhs <em>Rhs</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rhs</em>' containment reference.
   * @see #getRhs()
   * @generated
   */
  void setRhs(PTIdentifier value);

} // PTSignalAssign
