/*
 * generated by Xtext 2.35.0
 */
package org.xtext.example.hdl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.hdl.ui.internal.HdlActivator;

public class HDLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return HdlActivator.getInstance().getInjector("org.xtext.example.hdl.HDL");
	}

}
