/*
 * generated by Xtext 2.35.0
 */
package org.xtext.example.hdl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class HDLUiModule extends AbstractHDLUiModule {

	public HDLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
