/*
 * generated by Xtext 2.35.0
 */
package org.xtext.example.hdl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractHDLScopeProvider extends DelegatingScopeProvider {
}
